city_calendar:
    path:      /calendar/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:calendar }    
    requirements:
      _method: GET      

city_dancers:
    path:      /dancers/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:dancers }    
    requirements:
      _method: GET
      
city_teachers:
    path:      /teachers/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:teachers }    
    requirements:
      _method: GET
      
city_artists:
    path:      /artists/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:artists }    
    requirements:
      _method: GET      
      
city_bars:
    path:      /bars/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:bars }    
    requirements:
      _method: GET      

city_parties:
    path:      /parties/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:parties }    
    requirements:
      _method: GET 

city_shows:
    path:      /shows/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:shows }    
    requirements:
      _method: GET 

city_introductions:
    path:      /introductions/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:introductions }    
    requirements:
      _method: GET 

city_workshops:
    path:      /workshops/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:workshops }    
    requirements:
      _method: GET 
      
city_concerts:
    path:      /concerts/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:concerts }    
    requirements:
      _method: GET 
      
city_festivals:
    path:      /festivals/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:festivals }    
    requirements:
      _method: GET       

city_photos:
    path:      /photos/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:photos }    
    requirements:
      _method: GET  
      
city_musics:
    path:      /musics/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:musics }    
    requirements:
      _method: GET        
  
city_videos:
    path:      /videos/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:videos }    
    requirements:
      _method: GET            