city_dancers:
    path:      /city/dancers/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:dancers }    
    requirements:
      _method: GET
      
city_teachers:
    path:      /city/teachers/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:teachers }    
    requirements:
      _method: GET
      
city_artits:
    path:      /city/artits/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:artits }    
    requirements:
      _method: GET      

city_introductions:
    path:      /city/introductions/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:introductions }    
    requirements:
      _method: GET 

city_workshops:
    path:      /city/workshops/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:workshops }    
    requirements:
      _method: GET 
      
city_concerts:
    path:      /city/concerts/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:concerts }    
    requirements:
      _method: GET 
      
city_festivals:
    path:      /city/festivals/{searchcity}
    defaults:  { _controller: FrontFrontBundle:City:festivals }    
    requirements:
      _method: GET       
