front_event:
    path:     /
    defaults: { _controller: "FrontFrontBundle:Event:index" }

front_event_new:
    path:     /new
    defaults: { _controller: "FrontFrontBundle:Event:new" }

front_event_create:
    path:     /create
    defaults: { _controller: "FrontFrontBundle:Event:create" }
    requirements: { _method: post }

front_event_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:Event:edit" }

front_event_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:Event:update" }
    requirements: { _method: post|put }

front_event_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:Event:delete" }
    requirements: { _method: post|delete }
    
front_event_alerts:
    path:     /alerts/{id}
    defaults: { _controller: "FrontFrontBundle:Event:alerts" }    
    
front_event_loves:
    path:     /loves/{id}
    defaults: { _controller: "FrontFrontBundle:Event:loves" }    

front_event_love:
    path:     /love/{id}
    defaults: { _controller: "FrontFrontBundle:Event:love" }
    requirements: { _method: post }

front_event_unlove:
    path:     /unlove/{id}
    defaults: { _controller: "FrontFrontBundle:Event:unLove" }
    requirements: { _method: post }    
    
front_event_show:
    path:     /{uri}/{id}
    defaults: { _controller: "FrontFrontBundle:Event:show" }    