front_eventtype:
    path:     /
    defaults: { _controller: "FrontFrontBundle:EventType:index" }

front_eventtype_show:
    path:     /show/{id}
    defaults: { _controller: "FrontFrontBundle:EventType:show" }

front_eventtype_new:
    path:     /new/{id}
    defaults: { _controller: "FrontFrontBundle:EventType:new" }

front_eventtype_create:
    path:     /create
    defaults: { _controller: "FrontFrontBundle:EventType:create" }
    requirements: { _method: post }

front_eventtype_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:EventType:edit" }

front_eventtype_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:EventType:update" }
    requirements: { _method: post|put }

front_eventtype_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:EventType:delete" }
    requirements: { _method: post|delete }
