
front_event_new:
    path:     /new
    defaults: { _controller: "FrontFrontBundle:Event:new" }

front_event_create:
    path:     /create
    defaults: { _controller: "FrontFrontBundle:Event:create" }
    requirements: { _method: post }

front_event_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:Event:edit" }

front_event_edit_description:
    path:     /edit_description/{id}
    defaults: { _controller: "FrontFrontBundle:Event:editDescription" }

front_event_edit_dates:
    path:     /edit_dates/{id}
    defaults: { _controller: "FrontFrontBundle:Event:editDates" }

front_event_edit_links:
    path:     /edit_links/{id}
    defaults: { _controller: "FrontFrontBundle:Event:editLinks" }

front_event_edit_pictures:
    path:     /edit_pictures/{id}
    defaults: { _controller: "FrontFrontBundle:Event:editPictures" }

front_event_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:Event:update" }
    requirements: { _method: post|put }
    
front_event_update_link:
    path:     /update_link/{id}
    defaults: { _controller: "FrontFrontBundle:Event:updateLink" }
    requirements: { _method: post|put }      
    
front_event_update_description:
    path:     /update_description/{id}
    defaults: { _controller: "FrontFrontBundle:Event:updateDescription" }
    requirements: { _method: post|put }      

front_event_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:Event:delete" }
    requirements: { _method: post|delete }
    
front_event_alerts:
    path:     /alerts/{id}
    defaults: { _controller: "FrontFrontBundle:Event:alerts" }  
    
front_event_show:
    path:     /{uri}/{id}
    defaults: { _controller: "FrontFrontBundle:Event:show" }    