front_eventdate:
    path:     /
    defaults: { _controller: "FrontFrontBundle:EventDate:index" }

front_eventdate_show:
    path:     /{id}/show
    defaults: { _controller: "FrontFrontBundle:EventDate:show" }

front_eventdate_new:
    path:     /{id}/new
    defaults: { _controller: "FrontFrontBundle:EventDate:new" }

front_eventdate_create:
    path:     /{id}/create
    defaults: { _controller: "FrontFrontBundle:EventDate:create" }
    requirements: { _method: post }

front_eventdate_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontFrontBundle:EventDate:edit" }

front_eventdate_update:
    path:     /{id}/update
    defaults: { _controller: "FrontFrontBundle:EventDate:update" }
    requirements: { _method: post|put }

front_eventdate_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontFrontBundle:EventDate:delete" }
    requirements: { _method: post|delete }
    
front_eventdate_add_by_weekday:
    path:     /{id}/add_by_weekday
    defaults: { _controller: "FrontFrontBundle:EventDate:addByWeekday" }
