        
facebook_test:
    path:      /facebook_test
    defaults:  { _controller: FrontFrontBundle:Facebook:test }     
    
facebook_import_event_page:
    path:      /import_event_page
    defaults:  { _controller: FrontFrontBundle:Facebook:importEventPage }    
    requirements:
      _method: GET
      
facebook_preview_import_events:
    path:      /preview_import_events
    defaults:  { _controller: FrontFrontBundle:Facebook:previewImportEvents }    
    requirements:
      _method: POST
      
facebook_preview_import_event:
    path:      /preview_import_event
    defaults:  { _controller: FrontFrontBundle:Facebook:previewImportEvent }    
    requirements:
      _method: POST
      
facebook_import_events:
    path:      /import_events
    defaults:  { _controller: FrontFrontBundle:Facebook:importEvents }    
    requirements:
      _method: POST

facebook_show_import_button:
    path:      /show_import_button
    defaults:  { _controller: FrontFrontBundle:Facebook:showImportButton } 

facebook_import_week_events:
    path:      /show_week_events
    defaults:  { _controller: FrontFrontBundle:Facebook:importWeekEvents } 