front_move:
    path:     /
    defaults: { _controller: "FrontFrontBundle:Move:index" }

front_move_show:
    path:     /show/{id}
    defaults: { _controller: "FrontFrontBundle:Move:show" }

front_move_new:
    path:     /new
    defaults: { _controller: "FrontFrontBundle:Move:new" }

front_move_create:
    path:     /create
    defaults: { _controller: "FrontFrontBundle:Move:create" }
    requirements: { _method: post }

front_move_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:Move:edit" }

front_move_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:Move:update" }
    requirements: { _method: post|put }

front_move_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:Move:delete" }
    requirements: { _method: post|delete }
