front_musictype:
    path:     /
    defaults: { _controller: "FrontFrontBundle:MusicType:index" }

front_musictype_show:
    path:     /show/{id}
    defaults: { _controller: "FrontFrontBundle:MusicType:show" }

front_musictype_new:
    path:     /new
    defaults: { _controller: "FrontFrontBundle:MusicType:new" }

front_musictype_create:
    path:     /create/{id}
    defaults: { _controller: "FrontFrontBundle:MusicType:create" }
    requirements: { _method: post }

front_musictype_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:MusicType:edit" }

front_musictype_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:MusicType:update" }
    requirements: { _method: post|put }

front_musictype_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:MusicType:delete" }
    requirements: { _method: post|delete }
    
front_musictype_filters:
    path:     /filters
    defaults: { _controller: "FrontFrontBundle:MusicType:filters" }    
    
front_musictype_list_for_user_search:
    path:     /list_for_user_search/
    defaults: { _controller: "FrontFrontBundle:MusicType:listForUserSearch" }    
