
front_music_show:
    path:     /show/{id}
    defaults: { _controller: "FrontFrontBundle:Music:show" }
    
front_music_show_with_buttons:
    path:     /show_with_buttons/{id}
    defaults: { _controller: "FrontFrontBundle:Music:showWithButtons" }

front_music_new:
    path:     /new/{id}
    defaults: { _controller: "FrontFrontBundle:Music:new" }

front_music_create:
    path:     /create/{id}
    defaults: { _controller: "FrontFrontBundle:Music:create" }
    requirements: { _method: post }   

front_music_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:Music:edit" }

front_music_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:Music:update" }
    requirements: { _method: post|put }

front_music_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:Music:delete" }
    requirements: { _method: post|delete }
