    
front_musictype_filters:
    path:     /filters
    defaults: { _controller: "FrontFrontBundle:MusicType:filters" }    
    
front_musictype_list_for_user_search:
    path:     /list_for_user_search/
    defaults: { _controller: "FrontFrontBundle:MusicType:listForUserSearch" }    
