front_music:
    path:     /
    defaults: { _controller: "FrontFrontBundle:Music:index" }

front_music_show:
    path:     /{id}/show
    defaults: { _controller: "FrontFrontBundle:Music:show" }

front_music_new:
    path:     /{id}/new
    defaults: { _controller: "FrontFrontBundle:Music:new" }

front_music_create:
    path:     /{id}/create
    defaults: { _controller: "FrontFrontBundle:Music:create" }
    requirements: { _method: post }   

front_music_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontFrontBundle:Music:edit" }

front_music_update:
    path:     /{id}/update
    defaults: { _controller: "FrontFrontBundle:Music:update" }
    requirements: { _method: post|put }

front_music_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontFrontBundle:Music:delete" }
    requirements: { _method: post|delete }
