front_user_show_private:
    path:     /my-profile/
    defaults: { _controller: "FrontFrontBundle:User:showPrivate" }

front_user_edit:
    path:     /profile/edit/{id}
    defaults: { _controller: "FrontFrontBundle:User:edit" }
  
front_user_update_profile:
    path:     /profile/update_profile/{id}
    defaults: { _controller: "FrontFrontBundle:User:updateProfile" }
    requirements: { _method: post|put }
    
front_user_update_description:
    path:     /profile/update_description/{id}
    defaults: { _controller: "FrontFrontBundle:User:updateDescription" }
    requirements: { _method: post|put }
    
front_user_update_link:
    path:     /profile/update_link/{id}
    defaults: { _controller: "FrontFrontBundle:User:updateLink" }
    requirements: { _method: post|put }  
    
front_user_update:
    path:     /profile/update/{id}
    defaults: { _controller: "FrontFrontBundle:User:update" }
    requirements: { _method: post|put }    
    
front_user_import_facebook_event:
    path:     /import_facebook_event/
    defaults: { _controller: "FrontFrontBundle:User:importFacebookEvent" }    

front_user_show_overviews:
    path:     /pofile/overviews/{id}
    defaults: { _controller: "FrontFrontBundle:User:showOverviews" }
    
front_user_show_overviews_profile:
    path:     /pofile/overviews_profile/{id}
    defaults: { _controller: "FrontFrontBundle:User:showOverviewsProfile" }
    
front_user_loves:
    path:     /profile/loves/{id}
    defaults: { _controller: "FrontFrontBundle:User:loves" }    

front_user_love:
    path:     /profile/love/{id}
    defaults: { _controller: "FrontFrontBundle:User:love" }
    requirements: { _method: post }

front_user_unlove:
    path:     /profile/unlove/{id}
    defaults: { _controller: "FrontFrontBundle:User:unLove" }
    requirements: { _method: post }        
    
front_user_passed_events:
    path:      /profile/passed_events
    defaults:  { _controller: FrontFrontBundle:User:passedEvents }  
    
front_user_next_events:
    path:      /profile/next_events
    defaults:  { _controller: FrontFrontBundle:User:nextEvents }  
    
front_user_show_public:
    path:      /profile/{username}/{id}
    defaults:  { _controller: FrontFrontBundle:User:showPublic }  
    
callback_username:
    path:      /callback_username/
    defaults:  { _controller: UserUserBundle:User:callbackUsername }
    
front_user_list_for_video_search:
    path:     /list_for_video_search/
    defaults: { _controller: "FrontFrontBundle:User:listForVideoSearch" }    
    
front_user_list_for_move_search:
    path:     /list_for_move_search/
    defaults: { _controller: "FrontFrontBundle:User:listForMoveSearch" }    
    
front_user_list_for_music_search:
    path:     /list_for_music_search/
    defaults: { _controller: "FrontFrontBundle:User:listForMusicSearch" }    