
front_video_show:
    path:     /show/{id}
    defaults: { _controller: "FrontFrontBundle:Video:show" }
    
front_video_show_with_buttons:
    path:     /show_with_buttons/{id}
    defaults: { _controller: "FrontFrontBundle:Video:showWithButtons" }

front_video_new:
    path:     /new/{id}
    defaults: { _controller: "FrontFrontBundle:Video:new" }

front_video_create:
    path:     /create/{id}
    defaults: { _controller: "FrontFrontBundle:Video:create" }
    requirements: { _method: post }

front_video_edit:
    path:     /edit/{id}
    defaults: { _controller: "FrontFrontBundle:Video:edit" }

front_video_update:
    path:     /update/{id}
    defaults: { _controller: "FrontFrontBundle:Video:update" }
    requirements: { _method: post|put }

front_video_delete:
    path:     /delete/{id}
    defaults: { _controller: "FrontFrontBundle:Video:delete" }
    requirements: { _method: post|delete }
