<?php

namespace Admin\AdminBundle\Entity;

/**
 * PageContentTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageContentTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
