<?php

namespace Admin\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository {

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('p')
                ->leftJoin('p.translations', 'pt', 'WITH', 'pt.locale = :locale')
                ->setParameter('locale', $locale);

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('p')
                ->leftJoin('p.translations', 'pt', 'WITH', 'pt.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("p.name", ":search"));
            $orQuery->add($query->expr()->like("pt.title", ":search"));
            $orQuery->add($query->expr()->like("pt.content", ":search"));
            $orQuery->add($query->expr()->like("pt.description", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

}
