language: php
php:
    - 5.5

before_script:
  - cp app/config/parameters.travis.yml app/config/parameters.yml
  - composer install --quiet
  - php app/console doctrine:database:create --env=test -q
  - php app/console doctrine:schema:create --env=test -q
  - php app/console doctrine:fixtures:load -n --env=test -q

script:
  - phpunit -c app

notifications:
  email:
    -  serviceclient@directdev.fr