user_user_admin_user:
    resource: "@UserUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

user_user_admin_userfile:
    resource: "@UserUserBundle/Resources/config/routing/userfile.yml"
    prefix:   /admin/userfile 
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group    
