admin_userfile:
    path:     /
    defaults: { _controller: "UserUserBundle:UserFile:index" }

admin_userfile_show:
    path:     /{id}/show
    defaults: { _controller: "UserUserBundle:UserFile:show" }

admin_userfile_new:
    path:     /new
    defaults: { _controller: "UserUserBundle:UserFile:new" }

admin_userfile_create:
    path:     /create
    defaults: { _controller: "UserUserBundle:UserFile:create" }
    requirements: { _method: post }

admin_userfile_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserUserBundle:UserFile:edit" }

admin_userfile_update:
    path:     /{id}/update
    defaults: { _controller: "UserUserBundle:UserFile:update" }
    requirements: { _method: post|put }

admin_userfile_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserUserBundle:UserFile:delete" }
    requirements: { _method: post|delete }