# translations   
jms_i18n_routing:
    default_locale: "%locale%"
    locales: [en, fr]
    strategy: custom    
    
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [] #example : [routes]
#            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]   

jms_di_extra:
    locations:
        all_bundles: true
#        bundles: [FooBundle, AcmeBlogBundle]
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"

        method_calls:
            setRouter: ["@router"]    
            
a2lix_translation_form:
    locales: [en, fr]       #  Locales of translations
    #required_locales: [fr]      #  Empty by default
    manager_registry: doctrine      # [3]
    templating: "A2lixTranslationFormBundle::default.html.twig"      #  The default template is Twitter Bootstrap compatible        
    
# form label translations    
elao_form_translation:
    auto_generate: true    