imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: false

security:
    firewalls:
        main:
            http_basic:  
                
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     localhost
        port:     "%database_port%"
        dbname:   project-salsa-test
        user:     root
        password: 
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
          string_functions:
            acos: DoctrineExtensions\Query\Mysql\Acos
            asin: DoctrineExtensions\Query\Mysql\Asin
            atan2: DoctrineExtensions\Query\Mysql\Atan2
            atan: DoctrineExtensions\Query\Mysql\Atan
            charlength: DoctrineExtensions\Query\Mysql\CharLength
            concatws: DoctrineExtensions\Query\Mysql\ConcatWs
            cos: DoctrineExtensions\Query\Mysql\Cos
            cot: DoctrineExtensions\Query\Mysql\Cot
            countif: DoctrineExtensions\Query\Mysql\CountIf
            dateadd: DoctrineExtensions\Query\Mysql\DateAdd
            datediff: DoctrineExtensions\Query\Mysql\DateDiff
            day: DoctrineExtensions\Query\Mysql\Day
            degrees: DoctrineExtensions\Query\Mysql\Degrees
            field: DoctrineExtensions\Query\Mysql\Field
            findinset: DoctrineExtensions\Query\Mysql\FindInSet
            groupconcat: DoctrineExtensions\Query\Mysql\GroupConcat
            ifelse: DoctrineExtensions\Query\Mysql\IfElse
            ifnull: DoctrineExtensions\Query\Mysql\IfNull
            matchagainst: DoctrineExtensions\Query\Mysql\MatchAgainst
            md5: DoctrineExtensions\Query\Mysql\Md5
            month: DoctrineExtensions\Query\Mysql\Month
            nullif: DoctrineExtensions\Query\Mysql\NullIf
            radians: DoctrineExtensions\Query\Mysql\Radians
            sha1: DoctrineExtensions\Query\Mysql\Sha1
            sha2: DoctrineExtensions\Query\Mysql\Sha2
            sin: DoctrineExtensions\Query\Mysql\Sin
            strtodate: DoctrineExtensions\Query\Mysql\StrToDate
            tan: DoctrineExtensions\Query\Mysql\Tan
            timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
            week: DoctrineExtensions\Query\Mysql\Week
            year: DoctrineExtensions\Query\Mysql\Year                
