# Avalanche Imagine (thumbnails)
liip_imagine:
    resolvers:
        default:
            web_path:
              web_root: %kernel.root_dir%/../www
              cache_prefix: media/cache
        aws_resolver:
            aws_s3:
                client_config:
                    credentials:
                        key:    %amazon.s3.key%
                        secret: %amazon.s3.secret%
                    region: %amazon.s3.region%
                    version: %amazon.s3.version%
                    scheme: %amazon.s3.scheme%
                bucket:     %amazon.s3.bucket%
#                get_options:
#                    scheme: %amazon.s3.scheme%
                put_options:
                    CacheControl: 'max-age=86400' 
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../www/
    driver:               gd
    cache:                %liip.cache.resolver%
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        home_user:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [250, 250] } 
                thumbnail: { size: [250, 250], mode: inbound }
        home_city:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [250, 250] } 
                thumbnail: { size: [250, 250], mode: inbound }
        home_festival:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [250, 250] } 
                thumbnail: { size: [250, 250], mode: inbound }
        loggedin:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                thumbnail: { size: [30, 30], mode: outbound }     
        card_profile_picture:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                thumbnail: { size: [55, 55], mode: outbound }  
        profile_photo:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [320, 320] } 
                thumbnail: { size: [320, 320], mode: inbound }
        member_photo:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [90, 90] } 
                thumbnail: { size: [90, 90], mode: inbound }
        member_min_thumb:        
            quality:              80
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [34, 34] } 
                thumbnail: { size: [34, 34], mode: inbound }
        event_carrousel:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [973, 615] } 
                thumbnail: { size: [973, 615], mode: inbound }
        city_thumb:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                thumbnail: { size: [100, 100], mode: outbound }         
        city_thumb_large:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                thumbnail: { size: [150, 150], mode: outbound }         
        event:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                # min size
                upscale: { min: [389, 389] } 
                thumbnail: { size: [389, 389], mode: outbound }         
        facebook_imported_event:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                # min size
                upscale: { min: [480, 302] } 
                thumbnail: { size: [480, 302], mode: outbound }         
        navbar:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                upscale: { min: [40, 40] } 
                thumbnail: { size: [40, 40], mode: inbound }
        large:
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                downscale: { max: [973, 615] } 
        photo_masonry:        
            quality:              100
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                thumbnail: { size: [500, 500], mode: inbound }
        city_thumb:                
                
knp_gaufrette:
    adapters:
        aws_adapater:
            aws_s3:
                service_id: wds.amazon_s3
                bucket_name: %amazon.s3.bucket%               