# config geocode
bazinga_geocoder:
    fake_ip:
        enabled:              true
        ip:                   77.195.160.129 # fake ip for dev local test to remove in prod
        priority:             0
#    adapter:
#        class:                ~
    providers:
#        bing_maps:
#            api_key:              ~ # Required
#            locale:               ~
#        cache:
#            adapter:              ~ # Required
#            provider:             ~ # Required
#            locale:               ~
#            lifetime:             86400
#        ip_info_db:
#            api_key:              ~ # Required
#        cloudmade:
#            api_key:              ~ # Required
        google_maps:
            locale:               null
            region:               null
            use_ssl:              true
            api_key:              %google_map_api_key%
#        google_maps_business:
#            client_id:            ~ # Required
#            api_key:              null
#            locale:               null
#            region:               null
#            use_ssl:              false
#        openstreetmap:
#            locale:               ~
#        host_ip:              []
#        geoip:                []
        free_geo_ip:          []
#        mapquest:
#            api_key:              ~ # Required
#        oiorest:              []
#        geocoder_ca:          []
#        geocoder_us:          []
#        ign_openls:
#            api_key:              ~ # Required
#        data_science_toolkit:  []
#        yandex:
#            locale:               ~
#            toponym:              ~
#        geo_ips:
#            api_key:              ~
#        geo_plugin:           []
#        maxmind:
#            api_key:              ~ # Required
#        maxmind_binary:
#            binary_file:          ~ # Required
#            open_flag:            ~
#        chain:
#            providers:            []
        