
parameters:
#    parameter_name: value

services:
    wds.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method:  factory
        arguments:
            -
                credentials: { key: %amazon.s3.key%, secret: %amazon.s3.secret% }
                region: %amazon.s3.region%

    wds.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@acme.amazon_s3"
            - "%amazon.s3.bucket%"
            - "public-read" 
            - { scheme: %amazon.s3.scheme% }
            - { CacheControl: 'max-age=86400' }
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: %liip.cache.resolver% }
