admin_admin_homepage:
    path:      /
    defaults:  { _controller: AdminAdminBundle:Default:index }
    
AdminAdminBundle_page:
    resource: "@AdminAdminBundle/Resources/config/routing/page.yml"
    prefix: /page
    
AdminAdminBundle_pagecontent:
    resource: "@AdminAdminBundle/Resources/config/routing/pagecontent.yml"
    prefix: /pagecontent
    
AdminAdminBundle_address:
    resource: "@AdminAdminBundle/Resources/config/routing/address.yml"
    prefix:   /address            

AdminAdminBundle_city:
    resource: "@AdminAdminBundle/Resources/config/routing/city.yml"
    prefix:   /city 

AdminAdminBundle_country:
    resource: "@AdminAdminBundle/Resources/config/routing/country.yml"
    prefix:   /country        

AdminAdminBundle_event:
    resource: "@AdminAdminBundle/Resources/config/routing/event.yml"
    prefix:   /event        

AdminAdminBundle_eventdate:
    resource: "@AdminAdminBundle/Resources/config/routing/eventdate.yml"
    prefix:   /eventdate      

AdminAdminBundle_eventtype:
    resource: "@AdminAdminBundle/Resources/config/routing/eventtype.yml"
    prefix:   /eventtype      

AdminAdminBundle_musictype:
    resource: "@AdminAdminBundle/Resources/config/routing/musictype.yml"
    prefix:   /musictype       
    
AdminAdminBundle_video:
    resource: "@AdminAdminBundle/Resources/config/routing/video.yml"
    prefix:   /video

AdminAdminBundle_music:
    resource: "@AdminAdminBundle/Resources/config/routing/music.yml"
    prefix:   /music

AdminAdminBundle_tag:
    resource: "@AdminAdminBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

AdminAdminBundle_mea_user:
    resource: "@AdminAdminBundle/Resources/config/routing/meauser.yml"
    prefix:   /mea_user

AdminAdminBundle_mea_festival:
    resource: "@AdminAdminBundle/Resources/config/routing/meafestival.yml"
    prefix:   /mea_festival

AdminAdminBundle_mea_city:
    resource: "@AdminAdminBundle/Resources/config/routing/meacity.yml"
    prefix:   /mea_city

AdminAdminBundle_address:
    resource: "@AdminAdminBundle/Resources/config/routing/address.yml"
    prefix:   /address

AdminAdminBundle_address:
    resource: "@AdminAdminBundle/Resources/config/routing/address.yml"
    prefix:   /address
    
AdminAdminBundle_user_type:
    resource: "@AdminAdminBundle/Resources/config/routing/usertype.yml"
    prefix:   /user_type
    
AdminAdminBundle_user:
    resource: "@AdminAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user    