<?php

namespace Front\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository {

    public function findForFooter($limit = 6) {

        $query = $this->createQueryBuilder('c')
                ->where('c.footer = 1')
                ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

}
