<?php

namespace Front\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository {

    public function findForFooter($limit = 6) {

        $query = $this->createQueryBuilder('c')
                ->where('c.footer = 1')
                ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('c');

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('c')
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("c.name", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

}
