<?php

namespace Front\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {

    public function findOneByTitle($title = null) {
        if (!$title)
            return;
        $query = $this->createQueryBuilder('c')
                ->leftJoin('c.translations', 'ct')
                ->where("ct.title LIKE :title")
                ->setParameter('title', $title);
        return $query->getQuery()->getOneOrNullResult();
    }

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('c')
                ->leftJoin('c.translations', 'ct', 'WITH', 'ct.locale = :locale')
                ->setParameter('locale', $locale);

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('c')
                ->leftJoin('c.translations', 'ct', 'WITH', 'ct.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("c.name", ":search"));
            $orQuery->add($query->expr()->like("c.iso2", ":search"));
            $orQuery->add($query->expr()->like("ct.title", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

}
