<?php

namespace Front\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeRepository extends EntityRepository {

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('et')
                ->leftJoin('et.translations', 'ett', 'WITH', 'ett.locale = :locale')
                ->setParameter('locale', $locale);

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('et')
                ->leftJoin('et.translations', 'ett', 'WITH', 'ett.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("et.name", ":search"));
            $orQuery->add($query->expr()->like("ett.title", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }
    
    public function count() {
        $query = $this->createQueryBuilder('et')
                ->select('COUNT(et.id)');
        return $query->getQuery()->getSingleScalarResult();
    }

}
