<?php

namespace Front\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventDateRepository extends EntityRepository {

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('ed');

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('ed')
                ->leftJoin('ed.events', 'ede')
                ->leftJoin('ede.translations', 'edet', 'WITH', 'edet.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("ede.name", ":search"));
            $orQuery->add($query->expr()->like("edet.title", ":search"));
            $orQuery->add($query->expr()->like("edet.description", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

    public function count() {
        $query = $this->createQueryBuilder('ed')
                ->select('COUNT(ed.id)');
        return $query->getQuery()->getSingleScalarResult();
    }

}
