<?php

namespace Front\FrontBundle\Entity;

/**
 * MeaFestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeaFestivalRepository extends \Doctrine\ORM\EntityRepository {

    public function findForHomePage($limit = 3) {
        $query = $this->createQueryBuilder('mf')
                ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('mf')
                ->leftJoin('mf.translations', 'mft', 'WITH', 'mft.locale = :locale')
                ->setParameter('locale', $locale);

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('mf')
                ->leftJoin('mf.translations', 'mft', 'WITH', 'mft.locale = :locale')
                ->leftJoin('mf.event', 'mfe')
                ->leftJoin('mfe.translations', 'mfet', 'WITH', 'mfet.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("mft.description", ":search"));
            $orQuery->add($query->expr()->like("mfe.name", ":search"));
            $orQuery->add($query->expr()->like("mfet.title", ":search"));
            $orQuery->add($query->expr()->like("mfet.description", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

    public function count() {
        $query = $this->createQueryBuilder('mf')
                ->select('COUNT(mf.id)');
        return $query->getQuery()->getSingleScalarResult();
    }

}
