<?php

namespace Front\FrontBundle\Entity;

/**
 * MeaFestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeaFestivalRepository extends \Doctrine\ORM\EntityRepository
{
}
