<?php

namespace Front\FrontBundle\Entity;

/**
 * MeaUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeaUserRepository extends \Doctrine\ORM\EntityRepository
{
}
