<?php

namespace Front\FrontBundle\Entity;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveRepository extends \Doctrine\ORM\EntityRepository
{
}
