<?php

namespace Front\FrontBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository {

    public function findForAdmin($locale = 'en') {
        $query = $this->createQueryBuilder('t')
                ->leftJoin('t.translations', 'tt', 'WITH', 'tt.locale = :locale')
                ->setParameter('locale', $locale);

        return $query->getQuery();
    }

    public function filterAdmin($data, $locale = 'en') {
        $query = $this->createQueryBuilder('t')
                ->leftJoin('t.translations', 'tt', 'WITH', 'tt.locale = :locale')
                ->setParameter('locale', $locale)
                ->where("1 = 1");

        if (isset($data["search"])) {
            $orQuery = $query->expr()->orx();
            $orQuery->add($query->expr()->like("t.name", ":search"));
            $orQuery->add($query->expr()->like("tt.title", ":search"));
            $query->andWhere($orQuery);
            $query->setParameter('search', '%' . $data["search"] . '%');
        }

        return $query->getQuery();
    }

}
