
homepage:
    path:      /
    defaults:  { _controller: FrontFrontBundle:Default:index }
      
footer:
    path:      /footer
    defaults:  { _controller: FrontFrontBundle:Default:footer }      

policy:
    path:      /policy
    defaults:  { _controller: FrontFrontBundle:Default:policy }
    
FrontFrontBundle_user:
    resource: "@FrontFrontBundle/Resources/config/routing/user.yml"
    prefix:   /user      
    
FrontFrontBundle_address:
    resource: "@FrontFrontBundle/Resources/config/routing/address.yml"
    prefix:   /address             

FrontFrontBundle_dance:
    resource: "@FrontFrontBundle/Resources/config/routing/dance.yml"
    prefix:   /dance        

FrontFrontBundle_event:
    resource: "@FrontFrontBundle/Resources/config/routing/event.yml"
    prefix:   /event        

FrontFrontBundle_eventdate:
    resource: "@FrontFrontBundle/Resources/config/routing/eventdate.yml"
    prefix:   /eventdate      
    
FrontFrontBundle_eventlove:
    resource: "@FrontFrontBundle/Resources/config/routing/eventlove.yml"
    prefix:   /eventlove      
    
FrontFrontBundle_eventpresence:
    resource: "@FrontFrontBundle/Resources/config/routing/eventpresence.yml"
    prefix:   /eventpresence      
    
FrontFrontBundle_festival:
    resource: "@FrontFrontBundle/Resources/config/routing/festival.yml"
    prefix:   /festival      

FrontFrontBundle_landing:
    resource: "@FrontFrontBundle/Resources/config/routing/landing.yml"
    prefix:   /landing  
    
FrontFrontBundle_learn:
    resource: "@FrontFrontBundle/Resources/config/routing/learn.yml"
    prefix:   /learn  
    
front_front_front_music:
    resource: "@FrontFrontBundle/Resources/config/routing/music.yml"
    prefix:   /music
    
FrontFrontBundle_musictype:
    resource: "@FrontFrontBundle/Resources/config/routing/musictype.yml"
    prefix:   /musictype  
    
FrontFrontBundle_city:
    resource: "@FrontFrontBundle/Resources/config/routing/city.yml"
    prefix:   /city        

FrontFrontBundle_tag:
    resource: "@FrontFrontBundle/Resources/config/routing/tag.yml"
    prefix:   /tag         

FrontFrontBundle_usertype:
    resource: "@FrontFrontBundle/Resources/config/routing/usertype.yml"
    prefix:   /usertype         

front_front_front_video:
    resource: "@FrontFrontBundle/Resources/config/routing/video.yml"
    prefix:   /video