front_front_front_video:
    resource: "@FrontFrontBundle/Resources/config/routing/video.yml"
    prefix:   /video

front_front_front_music:
    resource: "@FrontFrontBundle/Resources/config/routing/music.yml"
    prefix:   /music

homepage:
    path:      /
    defaults:  { _controller: FrontFrontBundle:Default:index }
      
footer:
    path:      /footer
    defaults:  { _controller: FrontFrontBundle:Default:footer }      

policy:
    path:      /policy
    defaults:  { _controller: FrontFrontBundle:Default:policy }
    
FrontFrontBundle_user:
    resource: "@FrontFrontBundle/Resources/config/routing/user.yml"
    prefix:   /user      
    
FrontFrontBundle_address:
    resource: "@FrontFrontBundle/Resources/config/routing/address.yml"
    prefix:   /address        

FrontFrontBundle_country:
    resource: "@FrontFrontBundle/Resources/config/routing/country.yml"
    prefix:   /country        

FrontFrontBundle_dance:
    resource: "@FrontFrontBundle/Resources/config/routing/dance.yml"
    prefix:   /dance        

FrontFrontBundle_event:
    resource: "@FrontFrontBundle/Resources/config/routing/event.yml"
    prefix:   /event        

FrontFrontBundle_eventdate:
    resource: "@FrontFrontBundle/Resources/config/routing/eventdate.yml"
    prefix:   /eventdate      

FrontFrontBundle_eventtype:
    resource: "@FrontFrontBundle/Resources/config/routing/eventtype.yml"
    prefix:   /eventtype 
    
FrontFrontBundle_festival:
    resource: "@FrontFrontBundle/Resources/config/routing/festival.yml"
    prefix:   /festival      

FrontFrontBundle_musictype:
    resource: "@FrontFrontBundle/Resources/config/routing/musictype.yml"
    prefix:   /musictype  
    
FrontFrontBundle_city:
    resource: "@FrontFrontBundle/Resources/config/routing/city.yml"
    prefix:   /city        

FrontFrontBundle_tag:
    resource: "@FrontFrontBundle/Resources/config/routing/tag.yml"
    prefix:   /tag         

FrontFrontBundle_usertype:
    resource: "@FrontFrontBundle/Resources/config/routing/usertype.yml"
    prefix:   /usertype         
