
homepage:
    path:      /
    defaults:  { _controller: FrontFrontBundle:Default:index }
    
navbar:
    path:      /navbar
    defaults:  { _controller: FrontFrontBundle:Default:navbar } 
navbar_learn:
    path:      /navbar_learn
    defaults:  { _controller: FrontFrontBundle:Default:navbarLearn } 
navbar_discover:
    path:      /navbar_discover
    defaults:  { _controller: FrontFrontBundle:Default:navbarDiscover } 
navbar_meet:
    path:      /navbar_meet
    defaults:  { _controller: FrontFrontBundle:Default:navbarMeet } 
    
footer:
    path:      /footer
    defaults:  { _controller: FrontFrontBundle:Default:footer }      

policy:
    path:      /policy
    defaults:  { _controller: FrontFrontBundle:Default:policy }
    
FrontFrontBundle_user:
    resource: "@FrontFrontBundle/Resources/config/routing/user.yml"
    prefix:   /user   
    
FrontFrontBundle_userfile:
    resource: "@FrontFrontBundle/Resources/config/routing/userfile.yml"
    prefix:   /userfile      
    
FrontFrontBundle_address:
    resource: "@FrontFrontBundle/Resources/config/routing/address.yml"
    prefix:   /address             

FrontFrontBundle_dance:
    resource: "@FrontFrontBundle/Resources/config/routing/dance.yml"
    prefix:   /dance        

FrontFrontBundle_event:
    resource: "@FrontFrontBundle/Resources/config/routing/event.yml"
    prefix:   /event        

FrontFrontBundle_eventdate:
    resource: "@FrontFrontBundle/Resources/config/routing/eventdate.yml"
    prefix:   /eventdate      
    
FrontFrontBundle_eventlove:
    resource: "@FrontFrontBundle/Resources/config/routing/eventlove.yml"
    prefix:   /eventlove      
    
FrontFrontBundle_eventpresence:
    resource: "@FrontFrontBundle/Resources/config/routing/eventpresence.yml"
    prefix:   /eventpresence      
    
FrontFrontBundle_eventtype:
    resource: "@FrontFrontBundle/Resources/config/routing/eventtype.yml"
    prefix:   /eventtype  
    
FrontFrontBundle_eventfile:
    resource: "@FrontFrontBundle/Resources/config/routing/eventfile.yml"
    prefix:   /eventfile
    
FrontFrontBundle_facebook:
    resource: "@FrontFrontBundle/Resources/config/routing/facebook.yml"
    prefix:   /facebook      
    
FrontFrontBundle_festival:
    resource: "@FrontFrontBundle/Resources/config/routing/festival.yml"
    prefix:   /festival      

FrontFrontBundle_landing:
    resource: "@FrontFrontBundle/Resources/config/routing/landing.yml"
    prefix:   /landing  
    
FrontFrontBundle_learn:
    resource: "@FrontFrontBundle/Resources/config/routing/learn.yml"
    prefix:   /learn  
    
front_front_front_music:
    resource: "@FrontFrontBundle/Resources/config/routing/music.yml"
    prefix:   /music
    
FrontFrontBundle_musictype:
    resource: "@FrontFrontBundle/Resources/config/routing/musictype.yml"
    prefix:   /musictype  
    
FrontFrontBundle_city:
    resource: "@FrontFrontBundle/Resources/config/routing/city.yml"
    prefix:   /city        

FrontFrontBundle_tag:
    resource: "@FrontFrontBundle/Resources/config/routing/tag.yml"
    prefix:   /tag         

FrontFrontBundle_usertype:
    resource: "@FrontFrontBundle/Resources/config/routing/usertype.yml"
    prefix:   /usertype         

front_front_front_video:
    resource: "@FrontFrontBundle/Resources/config/routing/video.yml"
    prefix:   /video
