admin_event_file:
    path:     /
    defaults: { _controller: "AdminAdminBundle:EventFile:index" }

admin_event_file_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:EventFile:show" }

admin_event_file_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:EventFile:new" }

admin_event_file_create:
    path:     /create
    defaults: { _controller: "AdminAdminBundle:EventFile:create" }
    methods:  POST

admin_event_file_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:EventFile:edit" }

admin_event_file_update:
    path:     /{id}/update
    defaults: { _controller: "AdminAdminBundle:EventFile:update" }
    methods:  [POST, PUT]

admin_event_file_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:EventFile:delete" }
    methods:  [POST, DELETE]
    
admin_event_file_filter:
    path:     /filter_event_file
    defaults: { _controller: "AdminAdminBundle:EventFile:filter" }
    methods:  GET       
