admin_mea_user:
    path:     /
    defaults: { _controller: "AdminAdminBundle:MeaUser:index" }

admin_mea_user_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:MeaUser:show" }

admin_mea_user_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:MeaUser:new" }

admin_mea_user_create:
    path:     /create
    defaults: { _controller: "AdminAdminBundle:MeaUser:create" }
    methods:  POST

admin_mea_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:MeaUser:edit" }

admin_mea_user_update:
    path:     /{id}/update
    defaults: { _controller: "AdminAdminBundle:MeaUser:update" }
    methods:  [POST, PUT]

admin_mea_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:MeaUser:delete" }
    methods:  [POST, DELETE]
    
admin_mea_user_filter:
    path:     /filter_mea_user
    defaults: { _controller: "AdminAdminBundle:MeaUser:filter" }
    methods:  GET       
