admin_page:
    path:     /
    defaults: { _controller: "AdminAdminBundle:Page:index" }

admin_page_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:Page:show" }

admin_page_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:Page:new" }

admin_page_create:
    path:     /create
    defaults: { _controller: "AdminAdminBundle:Page:create" }
    requirements: { _method: post }

admin_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:Page:edit" }

admin_page_update:
    path:     /{id}/update
    defaults: { _controller: "AdminAdminBundle:Page:update" }
    requirements: { _method: post|put }

admin_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:Page:delete" }
    requirements: { _method: post|delete }
    
admin_page_filter:
    path:     /filter_page
    defaults: { _controller: "AdminAdminBundle:Page:filter" }
    methods:  GET       
