admin_user_type:
    path:     /
    defaults: { _controller: "AdminAdminBundle:UserType:index" }

admin_user_type_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:UserType:show" }

admin_user_type_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:UserType:new" }

admin_user_type_create:
    path:     /create
    defaults: { _controller: "AdminAdminBundle:UserType:create" }
    methods:  POST

admin_user_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:UserType:edit" }

admin_user_type_update:
    path:     /{id}/update
    defaults: { _controller: "AdminAdminBundle:UserType:update" }
    methods:  [POST, PUT]

admin_user_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:UserType:delete" }
    methods:  [POST, DELETE]
    
admin_user_type_filter:
    path:     /filter_user_type
    defaults: { _controller: "AdminAdminBundle:UserType:filter" }
    methods:  GET       
