admin_user_file:
    path:     /
    defaults: { _controller: "AdminAdminBundle:UserFile:index" }

admin_user_file_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:UserFile:show" }

admin_user_file_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:UserFile:new" }

admin_user_file_create:
    path:     /create
    defaults: { _controller: "AdminAdminBundle:UserFile:create" }
    methods:  POST

admin_user_file_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:UserFile:edit" }

admin_user_file_update:
    path:     /{id}/update
    defaults: { _controller: "AdminAdminBundle:UserFile:update" }
    methods:  [POST, PUT]

admin_user_file_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:UserFile:delete" }
    methods:  [POST, DELETE]
    
admin_user_file_filter:
    path:     /filter_user_file
    defaults: { _controller: "AdminAdminBundle:UserFile:filter" }
    methods:  GET       
